micronaut:
  application:
    name: microserver
  server:
    port:
      8040
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              #of course remove for the sake of prod security
              secret: 'ZmY4MDBlZTQ4MTRiYzM5Yjc5MDA1ZWJiOWI0OTYyNTcxZGUwNDI3ZDMyZTUzNzVjMjU0ODA0MzM0ZTQ0ZWVhYQ=='
              base64: true
              jws-algorithm: HS256
        bearer:
          enabled: true
        generator:
          access-token:
            expiration: 3600
    intercept-url-map:
      - pattern: /swagger/**
        http-method: GET
        access:
          - isAnonymous()

      - pattern: /favicon.ico
        http-method: GET
        access:
          - isAnonymous()


  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
        enabled: true

      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**




datasources:
  default:
    url: jdbc:postgresql://localhost:5432/microbase
    driverClassName: org.postgresql.Driver
    username: admin
    password: admin217
    schema-generate: none
    dialect: POSTGRES

flyway:
  datasources:
    default:
      enabled: true
      locations:
        classpath:migrations


kafka.bootstrap.servers: localhost:9092
